name: SpaceONE CI Tag
on:
  push:
    # recursive wild card
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      tag:
        # can replace github.event.inputs.tag <=> steps.getTag.outputs.tag
        default: 1.2.3

jobs:
  initialize:
    if: github.repository_owner == 'spaceone-dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: getTag

      - name: Set version
        run: |
          if [ ${{ steps.getTag.outputs.tag }} ]
          then
            echo "::set-env name=VERSION::${{ steps.getTag.outputs.tag }}"
          else
            echo "::set-env name=VERSION::${{ github.event.inputs.tag }}"
          fi

      - name: Set environment virables
        env:
          # LOCATION points the parent directory
          LOCATION_SETUP_PY: src # optional. for pypi upload
          LOCATION_VERSION: src # the location for VERSION file (ex- . means the location of VERSION is ./VERSION)
        run: |
          cat <<EOF>set_env.sh
          echo "::set-env name=LOCATION_SETUP_PY::$LOCATION_SETUP_PY"
          echo "::set-env name=LOCATION_VERSION::$LOCATION_VERSION"

          echo "::set-env name=VERSION::$VERSION"

          echo "$VERSION">$LOCATION_VERSION/VERSION
          EOF

          bash set_env.sh
          
      - name: save envs
        uses: actions/upload-artifact@v2
        with:
          name: set_env.sh
          path: set_env.sh

      - run: |
          cat set_env.sh

  pypi:
    if: github.repository_owner == 'spaceone-dev'
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: set_env.sh

      - name: Set environment variables
        run: |
          bash set_env.sh

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build
        run: |
          cd $LOCATION_SETUP_PY
          python setup.py sdist bdist_wheel

      - name: Upload Pypi
        id: upload
        run: |
          cd $LOCATION_SETUP_PY
          twine upload dist/*.whl --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --verbose

      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}